import { User, Objective, ProgressUpdate, Team } from "@/types";

export const MOCK_TEAMS: Team[] = [
  { id: "team-1", name: "Customer Success", manager_id: "user-2" },
];

export const MOCK_USERS: User[] = [
  {
    id: "user-1",
    email: "sarah@demo.com",
    full_name: "Sarah Chen",
    role: "employee",
    team_id: "team-1",
    avatar_initials: "SC",
  },
  {
    id: "user-2",
    email: "mike@demo.com",
    full_name: "Mike Rodriguez",
    role: "manager",
    team_id: "team-1",
    avatar_initials: "MR",
  },
  {
    id: "user-3",
    email: "alex@demo.com",
    full_name: "Alex Johnson",
    role: "employee",
    team_id: "team-1",
    avatar_initials: "AJ",
  },
];

export const MOCK_OBJECTIVES: Objective[] = [
  {
    id: "obj-1",
    owner_id: "user-1",
    owner_name: "Sarah Chen",
    team_id: "team-1",
    title: "Reduce early churn by improving 30-day onboarding",
    description:
      "Focus on activation milestones in the first 30 days to reduce churn from 18% to under 10%.",
    quarter: "Q2",
    year: 2026,
    status: "on_track",
    key_results: [
      {
        id: "kr-1",
        objective_id: "obj-1",
        title: "Increase 30-day activation rate",
        start_value: 42,
        target_value: 75,
        current_value: 61,
        unit: "%",
        created_at: "2026-04-01T09:00:00Z",
        updated_at: "2026-04-18T14:00:00Z",
      },
      {
        id: "kr-2",
        objective_id: "obj-1",
        title: "Complete onboarding playbook for top 3 segments",
        start_value: 0,
        target_value: 3,
        current_value: 2,
        unit: "playbooks",
        created_at: "2026-04-01T09:00:00Z",
        updated_at: "2026-04-20T11:00:00Z",
      },
      {
        id: "kr-3",
        objective_id: "obj-1",
        title: "Reduce time-to-first-value",
        start_value: 14,
        target_value: 5,
        current_value: 8,
        unit: "days",
        created_at: "2026-04-01T09:00:00Z",
        updated_at: "2026-04-22T10:00:00Z",
      },
    ],
    created_at: "2026-04-01T09:00:00Z",
    updated_at: "2026-04-22T10:00:00Z",
  },
  {
    id: "obj-2",
    owner_id: "user-1",
    owner_name: "Sarah Chen",
    team_id: "team-1",
    title: "Build a proactive health monitoring system",
    description:
      "Move from reactive support to predictive intervention using usage signals.",
    quarter: "Q2",
    year: 2026,
    status: "at_risk",
    key_results: [
      {
        id: "kr-4",
        objective_id: "obj-2",
        title: "Define and baseline 5 leading health indicators",
        start_value: 0,
        target_value: 5,
        current_value: 2,
        unit: "indicators",
        created_at: "2026-04-01T09:00:00Z",
        updated_at: "2026-04-15T09:00:00Z",
      },
      {
        id: "kr-5",
        objective_id: "obj-2",
        title: "Reduce accounts reaching red health without prior touch",
        start_value: 35,
        target_value: 10,
        current_value: 28,
        unit: "%",
        created_at: "2026-04-01T09:00:00Z",
        updated_at: "2026-04-19T16:00:00Z",
      },
    ],
    created_at: "2026-04-01T09:00:00Z",
    updated_at: "2026-04-19T16:00:00Z",
  },
  {
    id: "obj-3",
    owner_id: "user-3",
    owner_name: "Alex Johnson",
    team_id: "team-1",
    title: "Increase net revenue retention to 110%",
    description:
      "Drive expansion through upsells and cross-sells on existing accounts.",
    quarter: "Q2",
    year: 2026,
    status: "on_track",
    key_results: [
      {
        id: "kr-6",
        objective_id: "obj-3",
        title: "Close expansion deals in existing book",
        start_value: 0,
        target_value: 8,
        current_value: 5,
        unit: "deals",
        created_at: "2026-04-01T09:00:00Z",
        updated_at: "2026-04-21T13:00:00Z",
      },
      {
        id: "kr-7",
        objective_id: "obj-3",
        title: "Achieve NRR",
        start_value: 98,
        target_value: 110,
        current_value: 104,
        unit: "%",
        created_at: "2026-04-01T09:00:00Z",
        updated_at: "2026-04-21T13:00:00Z",
      },
    ],
    created_at: "2026-04-01T09:00:00Z",
    updated_at: "2026-04-21T13:00:00Z",
  },
  {
    id: "obj-4",
    owner_id: "user-3",
    owner_name: "Alex Johnson",
    team_id: "team-1",
    title: "Establish executive business reviews for tier-1 accounts",
    description: "Build exec-level relationships across our top 15 accounts.",
    quarter: "Q2",
    year: 2026,
    status: "off_track",
    key_results: [
      {
        id: "kr-8",
        objective_id: "obj-4",
        title: "Complete EBRs with tier-1 accounts",
        start_value: 0,
        target_value: 15,
        current_value: 3,
        unit: "EBRs",
        created_at: "2026-04-01T09:00:00Z",
        updated_at: "2026-04-10T09:00:00Z",
      },
    ],
    created_at: "2026-04-01T09:00:00Z",
    updated_at: "2026-04-10T09:00:00Z",
  },
];

export const MOCK_PROGRESS_UPDATES: ProgressUpdate[] = [
  {
    id: "pu-1",
    key_result_id: "kr-1",
    submitted_by: "user-1",
    submitted_by_name: "Sarah Chen",
    value: 61,
    note: "Completed onboarding flows for Enterprise segment. SMB segment on track for next week.",
    created_at: "2026-04-18T14:00:00Z",
  },
  {
    id: "pu-2",
    key_result_id: "kr-1",
    submitted_by: "user-1",
    submitted_by_name: "Sarah Chen",
    value: 52,
    note: "Initial baseline established after audit of current activation touchpoints.",
    created_at: "2026-04-10T09:30:00Z",
  },
  {
    id: "pu-3",
    key_result_id: "kr-2",
    submitted_by: "user-1",
    submitted_by_name: "Sarah Chen",
    value: 2,
    note: "Enterprise and Mid-Market playbooks done. SMB in draft review.",
    created_at: "2026-04-20T11:00:00Z",
  },
  {
    id: "pu-4",
    key_result_id: "kr-4",
    submitted_by: "user-1",
    submitted_by_name: "Sarah Chen",
    value: 2,
    note: "Defined login frequency and feature adoption as leading indicators. Working on support ticket volume and NPS.",
    created_at: "2026-04-15T09:00:00Z",
  },
];

export function getDemoCredentials() {
  return [
    { email: "sarah@demo.com", password: "demo123", label: "Sarah Chen (Employee)" },
    { email: "mike@demo.com", password: "demo123", label: "Mike Rodriguez (Manager)" },
    { email: "alex@demo.com", password: "demo123", label: "Alex Johnson (Employee)" },
  ];
}
